# Generated by Django 3.1.7 on 2023-04-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorizemodel',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
