# Generated by Django 3.1.7 on 2023-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invertedindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(blank=True, max_length=512, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('icon', models.CharField(blank=True, max_length=512, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'HtmlInfo',
            },
        ),
    ]
